### ISSUE TITLE
Copy-paste error in description (README.md)

### ISSUE THREAD

**Issue by sergey-belikov** [icza/screp#1]
README.md
Example to parse a file called sample.rep, and display replay header (included by default) and basic map data info (without tiles and resource location info):

++screp -map=true sample.rep
--s2prot -map=true sample.SC2Relay
Or simply:

++screp -map sample.rep
--s2prot -map sample.SC2Relay

**Comment by icza** [comment]
Thanks for reporting it, it is now fixed.
