### ISSUE TITLE
Error: index out of bounds

### ISSUE THREAD

**Issue by innerspirit** [icza/screp#15]
Hi, I've been using your tool and it seems that replays played on the official ladder map "(4)Gladiator1.1.rep" give an error as follows

`2019/08/20 21:21:45 Parsing error: runtime error: index out of range`
`Failed to parse replay: parsing`

**Comment by icza** [comment]
Can you give me such a replay that causes this error? Thanks.

**Comment by innerspirit** [comment]
Here is one
[rere.zip](https://github.com/icza/screp/files/3525116/rere.zip)

**Comment by icza** [comment]
Thanks for the rep. Fixed the issue and released [v1.1.1](https://github.com/icza/screp/releases/tag/v1.1.1).
