### ISSUE TITLE
Add game result to header

### ISSUE THREAD

**Issue by mekhami** [icza/screp#2]
That's all :)

**Comment by icza** [comment]
A new `Replay.Computed` field has been added. This wrapper contains -among others- the game leave commands. I believe this solves this issue.

You can parse a replay, not printing commands, only the computed field which will give you the game leave actions. See commit 2fb2fa21e1cc89b417b6f0d60a9dd61ac461fb37.

Will be out with the next release. Closing the issue now.

**Comment by icza** [comment]
Also note that other fields will be added to `Computed`, including game result. This is just the first step.
