### ISSUE TITLE
Not working on XP anymore

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#20]
I've v1.0.1 and it was working on XP, I just noticed that the latest ver doesn't.
Could that be a change in the compilation method?

And also you didn't respond to https://github.com/icza/screp/issues/19, can I still hope?

**Comment by icza** [comment]
The latest screp version is built with Go 1.13, which does not support Windows XP anymore. The latest Go that still does support it is Go 1.10.

Which means if you want it to run on XP, you have to checkout the sources and use Go 1.10 to build / compile it. I do not wish to support XP myself.

Binaries built with Go 1.13 require Windows 7 as a minimum which I believe covers 99.9% of the users.

**Comment by captain-majid** [comment]
Yeah Win7,8,1 or 10 on most PCs, but XP is also still used widely (especially as a Virtual Machine for quick tests), but thanks for letting me know.
