### ISSUE TITLE
New since 1.18.8: Failed to parse replay: zlib: invalid header

### ISSUE THREAD

**Issue by mekhami** [icza/screp#3]
https://fbw-replays.s3.amazonaws.com/replays/FBW_ladder_56_rXgJJ7M.rep

This replay (and a few others) fails to parse and says the above error message. `Failed to parse replay: zlib: invalid header`. It was played on 1.18.8 on Battle.net US East, and I believe was just a melee game, on a standard iccup map.

Thanks for checking it out!

**Comment by icza** [comment]
Before digging deeper, are these replays watchable with the game?

**Comment by mekhami** [comment]
They are, I loaded them up and verified them before opening the issue.

**Comment by mekhami** [comment]
Any headway on this? I'm running a service that depends heavily on this.

**Comment by icza** [comment]
Didn't have time to do it before, looking into it now.

**Comment by icza** [comment]
Good news, cause identified and easily fixed. Fix will be out in the next release.

**Comment by icza** [comment]
And it's already out :) :
https://github.com/icza/screp/releases/tag/v1.0.1

**Comment by mekhami** [comment]
Thanks very much!
