### ISSUE TITLE
CORS for repmastered.app rss/atom feeds.

### ISSUE THREAD

**Issue by alexpineda** [icza/screp#30]
Because I'd like to fetch via ajax.

Could there be a way to automatically upload via ajax as well?

**Comment by icza** [comment]
What CORS headers do you need exactly?

And yes, you can upload via AJAX as well, check out the source of the upload page, all you need to do is submit an HTML form. I can add CORS headers to the upload page too if needed.

**Comment by alexpineda** [comment]
Ok I'll have a look at uploads. I think you can safely add `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Methods: GET, OPTIONS` for universal access to those static resources. Allowing my host specifically would be `Access-Control-Allow-Origin: http://localhost` since it's a locally hosted app, not sure if we want or even need to go that route though.

**Comment by icza** [comment]
OK, added CORS headers to feeds and to the upload page. Please check if it works for you now.

Note that if you try to use the upload functionality, you'll be uploading anonymously. If you wish to upload as a user, login in a browser and you have to attach the `authtoken` cookie to your requests. For this to work, I might need additional CORS fine-tuning.

**Comment by alexpineda** [comment]
Thanks. Works as expected. I'll update you on upload once I attempt that.

**Comment by alexpineda** [comment]
Would you be able to include the download link?

**Comment by icza** [comment]
When you upload something on the web page, once the upload is complete, the result HTML document contains direct links to the uploaded games.

**Comment by alexpineda** [comment]
Yes but I'd like to be able to download recent games also.

**Comment by alexpineda** [comment]
Oh ic. Personally it wouldn't matter but I guess in general the longest would be the appropriate choice.

**Comment by icza** [comment]
I don't plan to include the replay download link in the feeds, but there's the game details page (as the ID), which if you visit / fetch, contains the download link.

**Comment by alexpineda** [comment]
ok good enough
