### ISSUE TITLE
How to determine SC1 replay format (v16 or v17+/scr)

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#31]
I think the output json **Header/Engine** should contain that info, but ig its always BW.

**Comment by icza** [comment]
The `Header.Engine` field tells whether the game was played using Original StarCraft or the Brood War extension, therefore its value may be `SC` (for Original) or `BW` (for Extension).

**Comment by captain-majid** [comment]
Well nobody plays on (Original) anymore, except maybe just the campaign, so ig Header/Engine isn't very useful to refer to the Expansion (BW) which is almost all the replays, I mainly use SC v1.16, not v1.17+ (SCR), and I appreciate if the replay format can be distinguished between the two versions.

Also BWChart defines the Engine field as I'm expecting, it'll be more useful if you can change screp/repmastered.app this way:
![bwchart](https://user-images.githubusercontent.com/39866989/193169099-3bf9d91d-b854-4442-abad-b94e15ee84f3.png)

**Comment by icza** [comment]
The Original StarCraft is still popular amongst fastest players, so it is still useful.

But I agree the version info would also be useful. Note that the replay version is not stored in the replay. "Guessing" the replay version based on the replay date is unreliable as the date cannot be trusted. Some version "categories" can be distinguished which I will add to screp and repmastered.app.

**Comment by icza** [comment]
There ya go: https://github.com/icza/screp/releases/tag/v1.7.2
Added a `Header.Version` field, quoting its documentation:

	// Version contains information about the replay version.
	// Since version is not stored in replays, this only designates certain version ranges deducted from replay format.
	// Current possible values are:
	//   - "-1.16": version is 1.16 or older
	//   - "1.18-1.20": version is 1.18..1.20
	//   - "1.21+": version is 1.21 or newer
	Version string

**Comment by icza** [comment]
Also added to [repmastered.app](https://repmastered.app).

Details: https://repmastered.app/news

**Comment by captain-majid** [comment]
Great news, thanks.

**Comment by captain-majid** [comment]
Can you add stats to https://repmastered.icza.net/stats about which version of the SC the games were played on ? I would like to know how many of v16 replays are there.

**Comment by icza** [comment]
I don't think this info is useful/interesting, most people (like 99% or probably more) plays with the current version.
I don't plan to add stats for versions.

**Comment by captain-majid** [comment]
IMO the opposite is correct, its both useful/interesting, it's the version of the replay format (what else more important ? Its like the 1st replay property that should be mentioned, its like the OS we're using, we can't say that its 99% Windows 10+ bc Microsoft say that, we can at least check to be sure), maybe just add it once and don't update it again if it costs some resources.

**Comment by icza** [comment]
I run an aggregation to count different versions for all time (without breaking down to map classes and ladders), and post the results here for you.

**Comment by icza** [comment]
OK, here are the stats, hope you're satisfied. As suspected, 99+% plays the current (1.21+ version), and the stats below holds games of all time, filtering it to the last year would give even higher percent.

Engine distribution:

```
Engine       | Count    | Percent
-------------|----------|---------
ALL          | 83279777 | 100.00%
BW 1.21+     | 82461324 |  99.01%
BW 1.18-1.20 |    35649 |   0.04%
BW -1.16     |   539978 |   0.65%
SC 1.21+     |    97268 |   0.12%
SC 1.18-1.20 |       65 |   0.00%
SC -1.16     |   145493 |   0.17%
```
Version distribution (SC+BW combined):
```
Version   | Count    | Percent
----------|----------|---------
ALL       | 83279777 | 100.00%
1.21+     | 82558592 |  99.13%
1.18-1.20 |    35714 |   0.04%
-1.16     |   685471 |   0.82%
```
