### ISSUE TITLE
What Alliance & Vision commands mean ?

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#33]
The title.

**Comment by icza** [comment]
Are you asking what the parameters mean or the commands themselves?

**Comment by icza** [comment]
Alliance and Vision commands are recorded when a player changes alliance or vision sharing.

Parameters of [Alliance command](https://pkg.go.dev/github.com/icza/screp@v1.7.3/rep/repcmd#AllianceCmd) lists slot IDs of players the owner allied to, plus whether allied victory is checked (enabled).

Parameters of [Vision command](https://pkg.go.dev/github.com/icza/screp@v1.7.3/rep/repcmd#VisionCmd) lists slot IDs of players the owner shared vision with.

**Comment by captain-majid** [comment]
I mean the cmds, I get things like that in the .json file:
```js
{
        "Frame": 13055,
        "PlayerID": 0,
        "Type": {
          "Name": "Alliance",
          "ID": 14
        },
        "SlotIDs": "AQM=",
        "AlliedVictory": true
      },
      {
        "Frame": 13055,
        "PlayerID": 0,
        "Type": {
          "Name": "Vision",
          "ID": 13
        },
        "SlotIDs": "AQM="
      },
```
And I don't understand, the game started TvB and the alliance stayed the same the whole game ig, makes no sense to me to change now, and I don't know what the SlotIDs mean here.
[ICCUP 2v2 PvP.zip](https://github.com/icza/screp/files/9872832/ICCUP.2v2.PvP.zip)

**Comment by icza** [comment]
The players structure holds the SlotID for each player. The `SlotIDs` in the JSON output is the Base64 encoded representation of a byte array (an array of unsigned 8-bit values), each element being a SlotID, the ones the owner player set alliance with.

The example you posted: `AQM=` is the base64 encoded form of the byte array `[1 3]`. This means the owner set alliance with players being at slotID=1 and slotID=3.

When players open the Alliance and Vision box and click OK, even if they don't change any alliance or vision, an Alliance and Vision command may still be recorded in the replay.

**Comment by icza** [comment]
And the slotID=1 belongs to player `NewBei_lol`, and slotID=3 belongs to player `bulguksa0`, this is from the Players array of screp's output.

**Comment by captain-majid** [comment]
Nice explanation, but why SlotIDs isn't represented in a readable format, or how to convert it to such ?

**Comment by icza** [comment]
In Go I model the `SlotIDs` as a byte array (`[]byte`), and Go's default JSON encoder transfers byte arrays as their Base64 representation. You have to run a Base64 decoder to get back the byte array. All languages support Base64 encoding.

**Comment by icza** [comment]
Will change the marshaling process to output `SlotIDs` as number arrays, see https://github.com/icza/screp/issues/34
