### ISSUE TITLE
Is it possible to check users battletag?

### ISSUE THREAD

**Issue by jack-kjlee** [icza/screp#36]
Thanks for the tool (screp).
I enjoy startcraft-remastered with your screp.
I want a function that I can check user (in replay) battletag.
Is it possible?

**Comment by icza** [comment]
That info is not stored in replays.

**Comment by jack-kjlee** [comment]
thank you for your efforts.
Is it possible to port screp to python?

**Comment by jack-kjlee** [comment]
Since I think screp is better than bwchart.
I do this because I want to report the analyzed content in real time.

**Comment by icza** [comment]
Port how? Automatically? I don't know of a way. Manually? Of course, but that's a lot of effort.

What / how do you want to report in real time? Do you mean something like https://repmastered.app ?

**Comment by jack-kjlee** [comment]
Amazing site (https://repmastered.app/)!
I am a student who studies python and likes starcraft-remastered :).
For my python practice, I want to convert your code to python version.
Okay. Thank you for your helps!
Then, is there any github repository for https://repmastered.app/ ?

**Comment by icza** [comment]
https://repmastered.app is not (yet) open source.

**Comment by jack-kjlee** [comment]
Thank you for reply :)

**Comment by icza** [comment]
https://repmastered.app has AKA list support. But it's on a user basis: each user can manager player aliases after logging in. These aliases are private to the user.

I do not have a public alias list. If you know of one, tell me.

**Comment by captain-majid** [comment]
I only have AKAS for some maps (not players):

> 투혼=Fighting Spirit
> 파이썬=Python
> 피의 능선=Bloody Ridge
> 단장의 능선=Heartbreak Ridge
> 저격능선=Sniper Ridge
> 태풍의 눈=Eye of the Storm
> 철의 장막=Iron Curtain
> 백두대간=Peaks of Baekdu

Maybe this list can help for players: https://liquipedia.net/starcraft/Smurf/List

**Comment by NapaNova** [comment]
> Amazing site (https://repmastered.app/)! I am a student who studies python and likes starcraft-remastered :). For my python practice, I want to convert your code to python version. Okay. Thank you for your helps! Then, is there any github repository for https://repmastered.app/ ?

depends on what you are looking to do.

In my case I just compiled the screp project to screp.exe

And I run it as sub process in my python code, then I just get the result from it and do stuff with it, like checking match result etc, and other data processing I need.

**Comment by icza** [comment]
Closing due to age.
