### ISSUE TITLE
Doesn't print winner team in some replays.

### ISSUE THREAD

**Issue by jack-kjlee** [icza/screp#37]
hi.
I tried uploading my replays, but some replays do not show the winning team. Why?

https://repmastered.app/game/RWUAObBT7FOQhXRn2nd-71BWVCcMvHRHL9_8p1gvq-4

**Comment by icza** [comment]
Hi, this is in [repmastered FAQ](https://repmastered.app/faq):

> **Q: How is the game result (winners / losers) determined?**
> A: As noted above, replays do not store the information who won.
> Winners are calculated using the "largest remaining team wins" principle. repmastered.app determines the in-game teams, and tracks players leaving. The team that leaves last, or the largest remaining team is appointed the winner.
> Notes:
> - If there is a team full of computer players, the result will be marked "Unknown".
> - Having a chat message in the game improves winner detection accuracy. So do leave a chat message in your games 😉
> 

Note that this is not 100% accurate, and if the largest remaining teams are the same size (e.g. 2 teams remain with equal number of players), the winner may not be determined.

Also see related / possible duplicate #32.

**Comment by icza** [comment]
Last note: do keep uploading your replays. I always improve screp and repmastered.app, so even if the winner cannot be determined today, a future update may change that. And I apply new algorithms to all past replays too.

Also note that a game may have multiple replays (from multiple players from the game). Repmastered.app recognizes this, and if multiple replays are available for a game, that also increases the chance to be able to determine the correct winner, and have more accurate statistics.

**Comment by jack-kjlee** [comment]
In my case, screp.exe file, too.
The same alogorithm (detecting winning team) is applied on screp?

**Comment by icza** [comment]
Yes, screp is used as the replay parser engine for https://repmastered.app.
