### ISSUE TITLE
how to determine teams for AI random pairing matches

### ISSUE THREAD

**Issue by shenghsi** [icza/screp#38]
Hi, very nice tool.
We are trying to build an auto-rating system for a group of sc enthusiasts. We commonly use the AI random pairing map with use map settings mode.

We tried to figure out which players are in the same team. But the problem with AI map is that all players are in team 1.
Do you have any idea about how to figure this out?
I am attaching an example rep here.

[LastReplay.zip](https://github.com/icza/screp/files/10530836/LastReplay.zip)

**Comment by icza** [comment]
I think that highly depends on how the map is created, what triggers or code is used for selecting teams. I'm not familiar with map making, and this may require extracting more map data from replays than what screp currently does.

Looking at this replay exactly, `Alliance` commands could be used to identify teams, not sure it it would work in general.

https://repmastered.app/game/9Fj2LGWvVQBiNpFDaHmU5iTZ2TZYs6199X0PHKNA0Rw

Alliance commands:

Frame | Time | Player | Command | Params |
-- | -- | -- | -- | -- |
483 | 00:20 | [24H]WoBuLu | Alliance | [1 4 7], AlliedVictory |
528 | 00:22 | 6501 | Alliance | [0 2 3], AlliedVictory |
842 | 00:35 | [24H]MarinE | Alliance | [1 4 7], AlliedVictory |
1106 | 00:46 | [24H]WoBuLu | Alliance | [1 4 7], AlliedVictory |
1173 | 00:49 | [24H]MarinE | Alliance | [1 4 7], AlliedVictory |
1239 | 00:52 | [24H]MarinE | Alliance | [1 4 7], AlliedVictory |
1274 | 00:53 | [24H]MarinE | Alliance | [1 4 7], AlliedVictory |
3238 | 02:15 | 6501 | Alliance | [0 2 3], AlliedVictory |
10343 | 07:14 | 6501 | Alliance | [0 2 3], AlliedVictory |
15464 | 10:49 | [24H]WoBuLu | Alliance | [1 4 7], AlliedVictory |
22332 | 15:37 | [24H]MarinE | Alliance | [1 4 7], AlliedVictory |
23731 | 16:36 | [24H]MarinE | Alliance | [1 4 7], AlliedVictory |

Based on these, the teams are:

[24H]MarinE, [24H]Myth_Tale, [24H]WoBuLu
vs
lin860801, 6501, SCI)_TuRtLe

**Comment by shenghsi** [comment]
It works. 
Thank you very much!
