### ISSUE TITLE
Is it possible to check whether a specific unit is killed?

### ISSUE THREAD

**Issue by kbj1213** [icza/screp#39]
I wonder if it is possible that track a specific unit's die event in a game.

For example, at 14100 frame a probe is died by marine.

Is it possible?

**Comment by icza** [comment]
No, this is not possible. Replays do not record unit death events, only user commands. The game engine is required to calculate / track such data.

**Comment by kbj1213** [comment]
Thanks for answering. I thought that it would be possible track how many probes I killed in a game in total because we can see total scores when the game is finished.

**Comment by icza** [comment]
Yes, you can see it _in game_, because the game engine calculates / tracks it. But without using the game engine, it's not possible.
