### ISSUE TITLE
Spending Quotient (SQ)

### ISSUE THREAD

**Issue by Maradonna90** [icza/screp#4]
http://wiki.teamliquid.net/starcraft2/Spending_quotient
would love to have it.

**Comment by icza** [comment]
I would love that too, but unfortunately StarCraft: Brood War replays do not contain enough information to calculate SQ.

**Comment by Maradonna90** [comment]
Well maybe the Remaster adds something to it, although I doubt it.

**Comment by icza** [comment]
Closing due to age.
