### ISSUE TITLE
Is it possible to track who is the replay uploader?

### ISSUE THREAD

**Issue by kbj1213** [icza/screp#40]
Thanks for very interesting repslay analyzer.

There is the host of game and all players' information but I couldn't find the info about the replay provider.

I wonder whether it is possible to find who is the replay uploader in the output result of screp.

**Comment by icza** [comment]
Hi! Replays do not store who saved the replay. But in some cases it can be deduced from data stored in replays.

When the replay saver can be detected, it's included in the output. Check the "Computed" field, and inside that the "RepSaverPlayerID".

Note: replay saver can be detected if there are chat messages in the replay. Also note that if you're parsing the replay saved by an observer, you'll see `128` for the `RepSaverPlayerID`.
