### ISSUE TITLE
Hi, in this replay, team 2 is the winner, I wonder why team 1 is computed as winner here.

### ISSUE THREAD

**Issue by NapaNova** [icza/screp#41]
https://junvodannotestaf86.blob.core.windows.net/24hreplayhosting/414c2c2984cdc7f5ce8e17fe181df2b7.rep

Hi, in this replay, team 2 is the winner, I wonder why team 1 is computed as winner here.

**Comment by icza** [comment]
This is a duplicate of #32 

Also see the FAQ page: https://repmastered.app/faq, question **How is the game result (winners / losers) determined?**

In short: Replays do not store the information who won. Winners are calculated using the "largest remaining team wins" principle. screp / repmastered.app determines the in-game teams, and tracks players leaving. The team that leaves last, or the largest remaining team is appointed the winner.

**Comment by NapaNova** [comment]
Thank you! Got it , really appreciate your work, awesome stuff!
