### ISSUE TITLE
How could I convert frames to time?

### ISSUE THREAD

**Issue by kbj1213** [icza/screp#42]
I wonder how much 1 frame is matched to time in second?

I can only guess at how much time span 1 frame represents from the fact that 38813 frames are matched at 27:10.

**Comment by NapaNova** [comment]
Brood war is rendered 24 frames per minute, 24 * 60 frames = 1 minute If I am not mistaken.

**Comment by NapaNova** [comment]
I double checked this with in game duration and vs frames total in the dump, I am pretty positive about this.

**Comment by icza** [comment]
There are approximately ~23.81 frames in a second; 1 frame = 0.042 second = 42 ms to be exact.

**Comment by icza** [comment]
This is documented at [`repcore.Frame`](https://pkg.go.dev/github.com/icza/screp@v1.9.1/rep/repcore#Frame)

[`repcore.DurationToFrame()`](https://pkg.go.dev/github.com/icza/screp@v1.9.1/rep/repcore#Duration2Frame) can be used o convert arbitrary time to frames, and the [`Frame.Duration()`](https://pkg.go.dev/github.com/icza/screp@v1.9.1/rep/repcore#Frame.Duration) method does the reverse: it converts a frame value to time (duration).

**Comment by kbj1213** [comment]
I perfectely got it!
Thank you!
