### ISSUE TITLE
Is there exception case for RepSaverPlayerID?

### ISSUE THREAD

**Issue by kbj1213** [icza/screp#43]
In top v bottom game, I set off Alliance Victory.

After all of enemy quit the game, I set on Alliance Victory again.

Then I got victory and quit the game.

In this case, in the screp result data, RepSaverPlayerID is null.

Is there exception cases for saving RepSaverPlayerID?

**Comment by kbj1213** [comment]
For example, after get data from screp by this replay, I couldn't get replaySaverID[](url)
[test.zip](https://github.com/icza/screp/files/10830997/test.zip)

**Comment by icza** [comment]
Replay saver is not stored in replays explicitly. It can only be deduced if there are chat messages in the game.

The replay you linked has chat messages: https://repmastered.app/game/Hr0jK8z1QL3rEB3Evy1HL9zWleGTwR5LeEqJK6WOsn0?tab=chat

I uploaded the other test replay here: https://repmastered.app/game/cWgo0atu1_9o9DkKH5922SrrqjbccU7iuioQduHdy90
It does not have any chat messages.

So be sure to leave chat messages in game ;)
