### ISSUE TITLE
Map picture

### ISSUE THREAD

**Issue by Death-cord** [icza/screp#47]
Not sure what is the switch -mapgfx does, I'm expecting it can generate a picture of the map like what's in repmastered.app ? if not, can you add an option to do that ?

http://www.stormcoast-fortress.net/cntt/software/scmdraft/gallery/
Also, like Scmdraft do it, how about drawing overlays of buildable areas, high-ground levels, and maybe even walkable areas ? that would be great and highly insightful for quick map analysis, I asked the people there to add it, and they are already willing to help:
https://github.com/ShieldBattery/bw-chk/issues/11

**Comment by icza** [comment]
As the doc says: `screp -h`:

        -mapgfx
            print map graphics related data; valid with 'map'

It does not generate a map image, but it includes additional data required to actually draw the map image. Namely, if `-mapgfx` flag is provided, the following data is also parsed and included in the output:
- Placed units on the map, including resources, critters and other UMS-placed units.
- Sprites

Drawing the actual map image requires graphics included in StarCraft installation itself. Packing these with `screp` is not practical for multiple reasons:
1. They weight multiple MBs, would result in a huge executable binary.
2. They are copyrighted material of Blizzard.

Also note that `screp` intends to be a replay parser and analyzer tool, not a map analyzer tool.

Also note https://repmastered.app does most of this: it renders high resolution images of maps of replays, also with placed units and buildings, also buildings built by the players, even animated. Check the Map tab of replays.
