### ISSUE TITLE
Replay from a saved/loaded game doesn't work expectedly in game replay mode

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#49]
When I save a game, SC responds as if I ended the game and the replay is saved correctly, but if I try to load this saved file and then reSave/quit, the replay doesn't work expectedly in game replay mode and I get a Nexus with 4 idle workers, but Screp display replay data from the 2nd replay correctly.

This isn't an issue of Screp, but the game itself handles it weirdly, I wonder if (since Screp can read the data of the 2 replays correctly) there is a way to merge the 2 replays into a working one, by removing the header of the 2nd one or maybe by just taking the cmds from the 2nd replay and appending them to the 1st replay.

**Comment by icza** [comment]
Yes, I believe it's possible to merge 2 such replays. However my expertise is not on the level to do that. I do not have full knowledge of the replay format to _write_ it, only to _read_ it.
