### ISSUE TITLE
Do all the commands in orders.go actually saved in the .rep ?

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#51]
I've noticed that workers cmds are listed there from line 96 to 107 along with so many orders: https://github.com/icza/screp/blob/b35f110c66f27653d922fc2e748420fa08d34df1/rep/repcmd/orders.go#L96

But I doubt that all of those are saved in the replay, any clarification of what orders to expect in the generated .json file and what not ?

Also what about this: https://github.com/icza/screp/issues/50

**Comment by icza** [comment]
Not all end up in replays, some or many of these may just be part of network communication. Also some of these may not occur in a network game (e.g. played on Battle.net), but only e.g. in single player or campaign games.

I do not have a full list what to expect. You may check the commands parser what commands are modeled, and you can expect those in the JSON output.

**Comment by captain-majid** [comment]
Some important commands like Pause/Resume don't appear in .json, but logically they must end up in the .rep, can you expose them ?

**Comment by icza** [comment]
I don't think pause/resume commands are persisted, and I don't think logically they should be.

While the game is paused, the in-game timer is also paused, the game is not tied to game-independent global clock.
