### ISSUE TITLE
Unexpectedly low number of workers

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#52]
In this replay I found the SCV train count is very low than the actual game, screp says its 59 SCV train cmd, but I watched the replay with CoachAI and it showed 39 SCV at end + 23 lost SCV = 62, not to mention that this is a pro player (Hiya), and also the expected spam where he tries to train when out of minerals, etc... at least its should be as the real game, right ?

https://repmastered.app/game/ALN40QAcER3_TnWy7qh_AoEtiGZABHFZOjM7ESL2qRE

**Comment by icza** [comment]
I checked the replay from the parser engine, and I saw no parsing errors.

Being a pro player doesn't necessarily mean there should be spam train commands. When there is no mineral, the train command might not end up in the replay.

Also, are you sure the 39+23 lost is the correct number? Maybe he trained 39, and out of those 39 he lost 23?

**Comment by captain-majid** [comment]
> the train command might not end up in the replay.

How ?
Also CoachAI doesn't lie or anticipate, so I'm sure:
![up](https://github.com/icza/screp/assets/39866989/cfaea646-07d0-486a-8684-7e0f1e431052)

**Comment by icza** [comment]
OK, I do not know what CoachAI includes in the numbers, most likely the solution is simply that the initial 4 SCVs you start with are included in the SCV count. That gives us 4 + 59 Train SCV commands = 63, which is greater than 39 + 23 SCVs lost.

**Comment by captain-majid** [comment]
That seems to be the only explanation, how didn't I think of that ? thanks.
