### ISSUE TITLE
When spam is calculated ?

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#54]
I've played a game vs Computer and tried to reproduce some spam actions to see what do what, but nothing was recorded as "IneffKind" in the generated json file, I tried to play a longer game, still nothing, any idea ?

**Comment by icza** [comment]
The rules for inefficient commands are detailed here: https://repmastered.app/faq

> **Q: What is EAPM, and how is it calculated?**
> **A:** EAPM stands for Effective APM. EAPM excludes commands from the APM calculation that are considered to be ineffective such as:
> - Unit queue overflow: training units that cannot fit into the queue
> - "Immediately" (dt < ~0.8s) cancelling a unit or upgrade
> - Repeating certain commands too fast (dt < ~0.4s) such as Stop, Hold, Attack, Set Rally etc.
> - Changing selection or reselecting the same units too fast (dt < ~0.3s); note: double-tapping a hotkey group to center the group is **not** considered ineffective
> - Repeating certain commands (without time restriction) such as Morph, Upgrade, Merge Archon, Lift off, Cancel Build etc.
> - Repeating the same Hotkey Add or Assign command

**Comment by captain-majid** [comment]
I've read that FAQ, still don't know the issue, this is the replay, if it helps:
https://repmastered.app/game/Z0VXziju4YUy3XPF92sSplNRUMJn4h7dmJwnwG2g9zE?tab=players

**Comment by icza** [comment]
What don't you understand? Please ask a _specific_ question. Your commands are not marked as ineffective because no rule is matching those patterns.

**Comment by captain-majid** [comment]
I don't know actually, this is another example:
https://repmastered.app/game/wevM1SVAJwWYzdwCzW9BWLkplYf3dEdv49txO-rAYPg?tab=commands

I've tried to do a very fast Right Click while selecting a Nexus/Hatchery, to Set Rally, but sometimes its normal Right Click cmd like in the above replay, and other times its Targeted Order/RallyPointTile, I also tried to do unstoppable same Hotkey Assign to increase APM enormously, by leaving my fingers on Ctrl+1 or Ctrl+2 for long time, but I end up with 0 spam.

Maybe the real conundrum is that I didn't do any of the repetitive **Select** cmd between every Set Rally or Hotkey Assign, I didn't even change focus, so I don't know why the heck this **Select** cmd interrupts every spam action !!!

I even disabled CoachAI, which is a thing I never do, but still, maybe I'm protected from spam detection ? :smile:

**Comment by icza** [comment]
There is a "Select" action after each of your commands, that's probably a 3rd party software, not your doing. That's likely why no inefficient action is detected. Try to assign some units to a hotkey (e.g. 1), and press down the `1` key to spamm "selecting" it. It surely will end up as inefficient, unless something your computer keeps selecting units in between.

**Comment by captain-majid** [comment]
Nothing changed, but at least its not a screp issue, thanks for help.

**Comment by captain-majid** [comment]
Its not Screp issue, but can you help me write Go code to ignore those spam Selects ?

I figured maybe I want to do this around this line of code: https://github.com/icza/screp/main/repparser/repparser.go#L484, but I'm illiterate in Go (just can compile it), I simply want to ignore the spam Select cmd if UnitTags are the same as the previous ones:
```golang
if base.Type.ID == 9
     if previousTypeIDSelect_UnitTags == thisTypeIDSelect_UnitTags 
           Then ignore this cmd
```

**Comment by icza** [comment]
What do you mean by "ignore"? Mark it as "inefficient"? Avoid adding it to the cmd's slice?

**Comment by captain-majid** [comment]
Yes avoid it completely.

**Comment by icza** [comment]
That ` if previousTypeIDSelect_UnitTags == thisTypeIDSelect_UnitTags ` is non-trivial. You have to start looking back in the `cmds` slice, and check only commands of the same player. You also have to abort if another select-like command is encountered, e.g. "Hotkey select", or "TypeIDSelect121", or other actions that change the selection (e.g. "Merge Archon").

And if you find such a command, then you may use `slices.Equal()` to compare the 2 `UnitTags` slices. If they are equal, mark this intent that you don't want to add this command (e.g. in a variable, like `skipAddingCmd = true`. Then at the end of the loop where the command is added to the slice: `cs.Cmds = append(...`, check this `skipAddingCmd` variable and skip adding if it's true.

**Comment by captain-majid** [comment]
I just want to cache the previous UnitTags array/slice, I don't care if another select-like command is encountered, I want to just check `if base.Type.ID == 9`, whether by `slices.Equal()` or comparing the items inside both UnitTags arrays.

Problem more than being illiterate in Go and that its cumbersome for me to do that, is I'm afraid I'll break something without even knowing.

**Comment by icza** [comment]
That's what I'm telling: there may be another `type.id==9` select let's say 10 commands earlier, but after that there may be a "select add" which changes the selection. So even if the previous `id==9` command has the same unit tags as the current command, then they are not the same, skipping the current command based on this is false logic.

I don't know what you want to achieve by this, but without properly tracking all select-related and selection-changer commands this can't be what you want.

**Comment by captain-majid** [comment]
I think normal Select `type.id==9` is unique enough than "select add" which is type.id==10, they probably get merged together in the end in .json as a normal Select (id==9), but that's all I care about.

That's another replay with the problem, I only selected the CC and kept pressing down CTRL+0 and look whats happened !!, if you've better solution than what I've suggested go ahead, but I don't want to bother you more with an issue thats not even in your tool.

[_spamSelect.zip](https://github.com/user-attachments/files/24040529/_spamSelect.zip)
