### ISSUE TITLE
Can X & Y range be determined ?

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#55]
Some cmds comes with x & y of a 255-max low ceiling, others are that * 32. Ig biggest map size is 256x256.

So, if I want to format all of them to be low ceiling (< 256) by dividing high ceiling x&y like 1020x214 on 32, then I might later face high ceiling x&y that are both smaller than 256 (Can't determine range), any way to generalize this range/ceiling level? or maybe you can follow 1 model regarding x&y, I hope I'm making my self clear.

**Comment by icza** [comment]
There are 2 kinds of x and y coordinates.

One is a pixel coordinate, e.g. when you want to move units to a location.

The other is in "tile" range, e.g. when you want to place a building. You can't place a building to arbitrary pixel position, it must be placed aligned to tile coordinates.

Which one is used is a property of the command. E.g. "Right click" uses pixel coordinates, "Build" uses tile coordinates. I don't have a table which one is which, but I think it can easily be guessed.

**Comment by captain-majid** [comment]
Thanks, Ig I'm going to stop dividing X&Y / 32, and leave them as is.
