### ISSUE TITLE
PlayerID is sometimes misplaced as SenderSlotID in Chat cmds

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#56]
...

**Comment by icza** [comment]
There is no misplacement. The player ID of chat messages is always the replay saver. The sender slot ID is who actually sent the message.

**Comment by captain-majid** [comment]
That makes sense, I almost forgot that, so if I didn't use **SenderSlotID** to retrieve chat messages, I'll get wrong results.
Do you remember when or from where you got the idea of the replay saver ? that wasn't known to me until recent time.

**Comment by icza** [comment]
I get the replay saver ID from chat messages. It isn't recorded anywhere else to my knowledge.

**Comment by captain-majid** [comment]
I just had a conversation in the past with SCRChart author, he didn't know that replay saver can be known and said that you're just guessing that based on leave game cmds which can't be right, so I thought I'm the 1 who discovered how to get the replay origin (saver) and maybe then you borrowed that idea from me ? correct me if I'm wrong.
![2023-10-27_232846](https://github.com/icza/screp/assets/39866989/96f98a83-a1ac-4f99-bff7-998a9193c8dc)

**Comment by captain-majid** [comment]
I just found it on this release, which is almost 3 years after I added this feature to CoachAI, so I guess I discovered America 1st lol.
https://github.com/icza/screp/releases/tag/v1.7.0

**Comment by icza** [comment]
Yes that very well may be ;)

Before adding this, screp never claimed to know the replay saver. What you and MasterRey talk about above may be just who is the winner (that is based on tracking leave commands).

**Comment by captain-majid** [comment]
I was talking bout the replay origin/saver only, he was focusing on the winner and leave game cmds.

Also, Chat cmds saved like that will eventually make the number of cmds for the replay saver wrong/bigger, since he is the author of all chat messages that happened during the game, unless you do some exception to exclude them, I checked some replays in repmastered.app and found that more cmds added to a player for chat msgs that he didn't even send, maybe its not a big issue, but worth the mentioning.

**Comment by icza** [comment]
Yes, chat messages are not excluded, but usually players have thousands of commands, and having a couple of chat messages (most often less than 10) doesn't affect anything.
