### ISSUE TITLE
Cmds aren't sorted correctly when it happen in the same frame

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#57]
...
https://repmastered.app/game/z5_EDS3pj2VkAIfbGMQUDThGmo1LPjwKzAEyODcJIg0?tab=commands
In this replay player n.Die_jaed0ng in the frame 5 builds a Drone while his last selection was 3 units (Drones?) which is impossible, I think this should come later, bc last selection to builds a Drone must be Hatchery, or maybe the selection of 3 units was Larvae ?

**Comment by icza** [comment]
Commands are displayed in the order they are recorded in replays, they are not reordered.

The selected 3 units are 3 Larvas. There is no bug here.
