### ISSUE TITLE
v118 to pre118 conversion and vice-versa

### ISSUE THREAD

**Issue by dragonattack** [icza/screp#6]
Hi András,
It's out of the scope of this tool, but maybe you have some drafts for that.
It would be great to have possibility to create 1.16 or 1.18 compatible versions from replays.
Of course I'm talking about repacking only here, we'll test if it work out.

**Comment by icza** [comment]
I don't have any work on this, and even if I'd do it, I don't know if the reps would work in older versions of SC.

I mean there is an obvious change in how data is compressed inside the replay, but even if I would repack new replays with the old compression, I don't know if any other things have changed that would render new reps in old SC useless / invalid.

**Comment by icza** [comment]
Closing as this is a dup of #19
