### ISSUE TITLE
"Unload" cmd mentioned twice

### ISSUE THREAD

**Issue by captain-majid** [icza/screp#60]
https://github.com/icza/screp/blob/b35f110c66f27653d922fc2e748420fa08d34df1/rep/repcmd/types.go
2 items there are named the same name "Unload", I think you should distinguish one from the other ? bc sometimes the cmd "Unload" refers to transport unit unload (Shuttle, Dropship, Overlord), and sometimes it's a Bunker unload. Not sure if it solves the problem but still better.

**Comment by icza** [comment]
Afaik the same command may be used for both, and whether it's "Bunker unload" or "Dropship unload" depends on what unit is selected (which cannot be determined in all cases for certain just from a saved replay).
