### ISSUE TITLE
how do I play a replay from the command line? 

### ISSUE THREAD

**Issue by lpflhh** [icza/screp#63]
I would like to ask a question, not sure if it is appropriate to ask here, how do I play a replay from the command line? If my StarCraft: Remastered is located in d:/games/scr/, I try to use d:/games/scr/x86_64/starcraft.exe d:/lastreplay.rep command, which does not work

**Comment by icza** [comment]
I think pre-remastered it was possible like this:

    starcraft.exe -replay path/to/replay.rep

But this doesn't work anymore and I don't know if this is possible.

**Comment by lpflhh** [comment]
> I think pre-remastered it was possible like this:
> 
> ```
> starcraft.exe -replay path/to/replay.rep
> ```
> 
> But this doesn't work anymore and I don't know if this is possible.

thanks very much！
