### ISSUE TITLE
Outputting MM info

### ISSUE THREAD

**Issue by Ezro** [icza/screp#64]
I noticed that there's awesome data in repmastered for tracking MMR of a replay and even the players within the game. Is there a way to output the MM info (e.g., `2024 S2·KR·S2285`) using CLI?

**Comment by icza** [comment]
No, it's not possible because this info is not stored in replays.

RepMastered acquires this info on a separate channel (from Battle.net).

**Comment by Ezro** [comment]
> No, it's not possible because this info is not stored in replays.
> 
> RepMastered acquires this info on a separate channel (from Battle.net).

Ah that makes sense. Do you have guidance on how to grab from Battle.net?

**Comment by icza** [comment]
Just by having the replay, it's not possible. You have to know the internal ID of the game, and then you can "query" by that using a running StarCraft client. But the internal ID is also not stored in the replay. RepMastered does not fetch MM info for uploaded replays, it does it separately, and just pairs the collected MM info with the uploaded replays.

**Comment by Ezro** [comment]
> The StarCraft client launches an internal HTTP server which can be queried (it's not intended for 3rd parties, only for the StarCraft client itself). It's not documented and I'm not aware of any public libs that interact with it.

Woah, that's pretty wild. That seems like a good project to open source 😉
