### ISSUE TITLE
Would we be able to extract resource information from the .rep file (1.21)? And so how?

### ISSUE THREAD

**Issue by MichaelBakker1986** [icza/screp#66]

**Comment by icza** [comment]
No, replays do not store enough information to accurately tell how much resources players gather. The resources available on the map is available of course.

**Comment by MichaelBakker1986** [comment]
Would we be able to extract the current viewpoint per frame per player.

**Comment by icza** [comment]
No. Camera position and movement is also not recorded in replays.

**Comment by MichaelBakker1986** [comment]
So how does BW interpret the replays to replay the game? if this information is not available?

**Comment by icza** [comment]
When watching the replay, you have no option to see what players saw during the game (screen position). Exactly because this information is not recorded in replays.

**Comment by MichaelBakker1986** [comment]
I understand, but there are x,y coordinates of the current screen onrightclick etc.. But not the minimap poisition to determine what building is actually selected

**Comment by icza** [comment]
For the 3rd time: there are no screen coordinates in replays. Coordinates are either pixel coordinates on the map (not on the screen), or tile positions.

**Comment by MichaelBakker1986** [comment]
Oke that makes sense, the coordinates are the tile coordinates. Thanks for the information.
