### ISSUE TITLE
Input redirection into screp

### ISSUE THREAD

**Issue by msikma** [icza/screp#67]
Hi there. I was wondering if this is possible, or could potentially be added as a feature.

I think it'd be nice to be able to pipe data, e.g. `screp < myfile.rep`. I'm calling screp from inside Node JS and this would allow me to process in-memory file buffers without having to save them to a temp file.

**Comment by icza** [comment]
Santa comes early this year. Here's your wish: https://github.com/icza/screp/releases/tag/v1.12.10

Just provide the `-stdin` CLI flag, and replay will be expected on the standard input.

Cheers!

**Comment by msikma** [comment]
Thank you! It seems to work really well, thank you for adding it and creating a new release.
