### ISSUE TITLE
No APM field or how do you count it

### ISSUE THREAD

**Issue by dragonattack** [icza/screp#7]
just counting it like that:
```
Apm = TotalCommands / LastCommandFrame * 60;
```
giving slightly wrong results. for example: http://bwreplays.com/rtfhr

Total Frames: 13143, Total Time Sec: 548, Total Time Min: 9.1333
P Bonyth APM: **266**, Last Frame: 13124, Time: 547
Z InSneir APM: 317, Last Frame: 13054, Time: 544

BWreplays.com gives: Bonyth **236**, InSneir 318

How you do it? Thanks.

**Comment by icza** [comment]
Different applications calculate APMs differently. Some exclude the first X seconds. Others only include certain commans in calculating APM.

For an introduction, see this page: [Sc2gears: APM Types](https://sites.google.com/site/sc2gears/features/replay-analyzer/apm-types)

**Comment by icza** [comment]
Closing due to age.
