### ISSUE TITLE
Make building easier

### ISSUE THREAD

**Issue by mrcoles** [icza/screp#9]
Hi! I might just not know enough about go, but it seems like in order to build this project, I had to:

1. clone the repo under `$GOPATH/src/github.com/icza/`
2. cd into the `_release/`
3. run `bash release.sh`

Isn’t the standard build to be able to run something like `go install` from the root directory? Or LMK if I’m missing something (very possible 😄)

**Comment by icza** [comment]
screp follows the Go "standard", that is you can get and build the project by executing the simple command:

    go get github.com/icza/screp

Nothing else is required. The `release.sh` script is to build and pack the executable binaries for multiple platforms.

**Comment by mrcoles** [comment]
Oh haha, thank you. Really shows my lack of knowledge of Go 😏 . I proposed a PR to add that info to the README. Either way, thanks!
